### PR TITLE
Wiki

### LINKED ISSUE #38: Doesn't apply to the Wiki
Could this functionality be added to the Wiki too - tables are painful on narrow Github!

### PR DESCRIPTION
**Pull request by Martii**
For your consideration.

Been running this mod for about month now just to be sure. ~~Only one issue detected early on by visible looking... and noted... as an additive fix instead of removal for GH. Icon avatars are typically square even if the source isn't... including when pulled from gravatar.~~

NOTES:
* Needs version bump
* Needs `make all` run again to regenerate

Thanks for the look.

Closes #38

### CODE REVIEW

**Comment by Martii** [comment]
@xthexder 
Is this still something you are interesting in doing? Looks like GH resolved the Overview avatar issue.

**Comment by Martii** [comment]
Whoa... also affects Notifcations/Watching/Subscriptions. :)

**Comment by xthexder** [comment]
I'd like to include the wiki page, as well as a few other pages, but the thing stopping me so far has been that the Wiki doesn't have any unique class/id's, so this styling will be global to every github page. That's not an issue on its own, but it does mean I want to do a lot more testing. I'd rather some pages be fixed width than for all pages to be full width and some be broken.

**Comment by xthexder** [comment]
I pushed an update that changed from the page-specific container styling to a more general one that includes the wiki and pretty much every other page on the site.
After a bunch of browsing around I wasn't able to find any broken pages, but I'll keep an eye out for anything that's off.

**Comment by Martii** [comment]
Looks like there's some overlapping at https://github.com/ with the GH popup alerts... once they go away then it seems to self correct itself. Vertically near "Discover repositories" .

**Pull request closed without merging**
