### PR TITLE
Add Toggling Behaviour

### PR DESCRIPTION
**Pull request by jamiebrynes7**
One thing that I found slightly lacking (and common feedback on the Chrome Web Store) is the lack of a toggling solution.

This PR restructures the injection to be done programmatically rather than through `manifest.json`.  When toggled, all github or gist pages are automatically refreshed to reflect the change.

### CODE REVIEW

**Comment by tkrokli** [comment]
To me, it looks like the file `jquery-3.3.1.min.js` could do with more NewLine/Line Feed for better overview.
Or is it required to have the current formatting of only 2 lines?

**Comment by jamiebrynes7** [comment]
Its the minified version to reduce the file size, meant for use in production. You can unminify it here: http://unminify.com/

**Comment by tkrokli** [comment]
Thanks. I definitely see the point now.

**Comment by xthexder** [comment]
I would prefer if this didn't require jquery to be imported.
You can take a look at [wide-github.user.js](https://github.com/xthexder/wide-github/blob/master/wide-github.user.js) for an example on how to append html without jquery.
http://youmightnotneedjquery.com/ is also a good resource

Allowing toggling is definitely nice to have. I may look at setting up toggling behavior for userscripts/greasemonkey as well.

**Comment by jamiebrynes7** [comment]
@xthexder Thanks for the references, I'm pretty inexperienced with vanilla JS so don't know my way around too well. :) 

I've updated the PR to remove the dependency on jquery.

**Comment by xthexder** [comment]
Added in version 1.4.0 without requiring extra permissions.

**Pull request closed without merging**
