### PR TITLE
Refix SPDX

### PR DESCRIPTION
**Pull request by Martii**
See #26

### CODE REVIEW

**Comment by Martii** [comment]
whoops need to add to this... just a moment...

**Comment by Martii** [comment]
Think that's it from your commit history and a search. Thanks for the look.

OUJS Admin

**Comment by xthexder** [comment]
Whoops. Forgot this was an issue.
Thanks again!

**Comment by Martii** [comment]
No problem... I missed the make.js file the first round... didn't realize that you did it that way until a closer inspection. Should catch it in the future since I searched for `MIT` on your repo. Thank you!!! Couldn't live well without this script on GH... too narrow without it. :)

**Pull request merged**
